name: Deploy to ECS

on:
  push:
    branches: [main]  

permissions:
  id-token: write  
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::186091750176:role/github
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push backend image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_DATABASE_REPO: rustbase-atlas
        ECR_BACKEND_REPO: rustbase-backend
        ECR_FRONTEND_REPO: rustbase-frontend
      run: |
        docker compose build 

        # Tag them for ECR
        docker tag rustbase-atlas:latest $ECR_REGISTRY/$ECR_DATABASE_REPO:latest
        docker tag rustbase-backend:latest $ECR_REGISTRY/$ECR_BACKEND_REPO:latest
        docker tag rustbase-ui:latest $ECR_REGISTRY/$ECR_FRONTEND_REPO:latest
        
        # Push 
        docker push $ECR_REGISTRY/$ECR_DATABASE_REPO:latest
        docker push $ECR_REGISTRY/$ECR_BACKEND_REPO:latest
        docker push $ECR_REGISTRY/$ECR_FRONTEND_REPO:latest

    - name: Run Atlas migrations
      env:
        SUBNET_ID: ${{ secrets.SUBNET_ID }}
        SECURITY_ID: ${{ secrets.SECURITY_ID }}
        CLUSTER: rustbase
        TASK: rustbase-atlas 
      run: |
        TASK_ARN=$(aws ecs run-task \
          --cluster $CLUSTER \
          --task-definition $TASK \
          --launch-type FARGATE \
          --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_ID],securityGroups=[$SECURITY_ID],assignPublicIp=DISABLED}" \
          --query 'tasks[0].taskArn' \
          --output text)
        
        echo "Waiting for migration to complete..."
        aws ecs wait tasks-stopped --cluster $CLUSTER --tasks $TASK_ARN

    - name: Update ECS backend service
      env:
        CLUSTER: rustbase
        SERVICE: rustbase-backend-service
      run: |
        aws ecs update-service \
          --cluster $CLUSTER \
          --service $SERVICE \
          --force-new-deployment

    - name: Update ECS frontend service
      env:
        CLUSTER: rustbase
        SERVICE: rustbase-frontend-service
      run: |
        aws ecs update-service \
          --cluster $CLUSTER \
          --service $SERVICE \
          --force-new-deployment

